name: Boholm Photography
favicon: null
layout_spectrum: 0.4286378107499331
typography_spectrum: 0.3771190328989178
title: Boholm Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.33393613109365106
  lightness: 0.7415639890823513
  saturation: 0.4527432583272457
  rhythmicContrast: 0.8947480204515159
purpose: []
